spring.config.activate.on-profile=docker

spring.datasource.url=jdbc:postgresql://postgres:5432/orderflow
spring.rabbitmq.host=rabbitmq

orderflow.rabbitmq.exchange-name=order.events
orderflow.rabbitmq.queue-inventory=order.inventory
orderflow.rabbitmq.queue-email=order.email
orderflow.rabbitmq.routing-key-order-created=order.created
